import { motion } from "framer-motion";
import { ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { Link } from "react-router-dom";
import ThemeToggle from "../components/ThemeToggle";
import { useSite } from "../context/SiteContext";
export default function MaintenancePage() {
  const { content } = useSite();
  return <main className="maintenance-page relative flex min-h-screen overflow-hidden px-5 py-6 text-white">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_35%,rgba(96,81,155,.22),transparent_38%)]" />
    <motion.div className="absolute left-[12%] top-[18%] h-52 w-52 rounded-full border border-orange-400/15" animate={{ scale: [1, 1.16, 1], opacity: [.25, .65, .25] }} transition={{ duration: 5, repeat: Infinity }} />
    <motion.div className="absolute bottom-[12%] right-[8%] h-72 w-72 rounded-full border border-orange-300/10" animate={{ scale: [1.15, 1, 1.15], rotate: [0, 25, 0] }} transition={{ duration: 8, repeat: Infinity }} />
    <header className="absolute inset-x-0 top-0 z-20 flex items-center justify-between p-5 sm:p-8"><div className="flex items-center gap-3"><img src={content.logoUrl || "/images/gotham-emblem-static.jpg"} alt="" className="h-10 w-10 rounded-full object-cover ring-1 ring-orange-300/30" /><span className="font-serif text-sm tracking-[.18em] sm:text-base">{content.siteName}</span></div><div className="flex items-center gap-2"><ThemeToggle /><Link to="/login" className="inline-flex items-center gap-2 rounded-xl border border-orange-300/30 bg-orange-400/10 px-3 py-2 text-xs font-semibold text-orange-200 backdrop-blur-xl transition hover:bg-orange-400/20 sm:px-4 sm:text-sm"><ShieldCheck size={16} /> Admin login</Link></div></header>
    <div className="relative z-10 m-auto max-w-2xl text-center"><motion.div initial={{ opacity: 0, scale: .7, rotate: -10 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ type: "spring", duration: 1 }} className="mx-auto mb-8 flex h-24 w-24 items-center justify-center rounded-3xl border border-orange-300/25 bg-orange-400/10 shadow-[0_0_70px_rgba(96,81,155,.28)] backdrop-blur-xl"><motion.div animate={{ rotate: [0, -9, 9, 0] }} transition={{ duration: 2.6, repeat: Infinity, repeatDelay: 1 }}><Wrench size={42} className="text-orange-200" /></motion.div></motion.div><motion.h1 initial={{ y: 24, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .2 }} className="font-serif text-4xl font-bold tracking-tight sm:text-6xl">The city is being upgraded.</motion.h1><motion.p initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: .35 }} className="mx-auto mt-6 max-w-xl text-base leading-7 text-white/60 sm:text-lg">We are performing scheduled maintenance to make your next visit smoother. Public access is temporarily closed—please check back shortly.</motion.p><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .6 }} className="mt-10 inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/5 px-5 py-3 text-sm text-white/65 backdrop-blur-xl"><Sparkles size={16} className="text-orange-300" /><span>Systems are receiving a little Gotham polish</span><span className="flex gap-1"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-orange-300" /><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-orange-300 [animation-delay:200ms]" /><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-orange-300 [animation-delay:400ms]" /></span></motion.div></div>
  </main>;
}
