import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

type Language = "en" | "ar";

const AR: Record<string, string> = {
  Home: "الرئيسية",
  Server: "الخادم",
  Roster: "الطاقم",
  Live: "البث المباشر",
  Journey: "القصة",
  News: "الأخبار",
  Careers: "التوظيف",
  FAQ: "الأسئلة الشائعة",
  Characters: "الشخصيات",
  Dashboard: "لوحة اللاعب",
  Login: "تسجيل الدخول",
  Register: "إنشاء حساب",
  Admin: "الإدارة",
  "Admin Panel": "لوحة الإدارة",
  "Join Discord": "انضم إلى ديسكورد",
  "Save All Changes": "حفظ كل التغييرات",
  "Saving...": "جار الحفظ...",
  "View Site": "عرض الموقع",
  Logout: "تسجيل الخروج",
  "Back to site": "العودة للموقع",
  "Access Denied": "تم رفض الوصول",
  "You need admin permissions to view this page.": "تحتاج إلى صلاحيات الإدارة لعرض هذه الصفحة.",
  Homepage: "الصفحة الرئيسية",
  Partners: "الشركاء",
  "Server / Features": "الخادم والمميزات",
  Streamers: "البثوث",
  "Famous Chars": "الشخصيات المشهورة",
  "Journey & Chars": "القصة والشخصيات",
  Applications: "الطلبات",
  Tickets: "التذاكر",
  Comments: "التعليقات",
  "Theme & Brand": "الهوية والألوان",
  Terms: "الشروط",
  Users: "المستخدمون",
  "Staff & Roles": "الإدارة والصلاحيات",
  Settings: "الإعدادات",
  "Audit Logs": "سجل الإدارة",
  "Homepage Partners": "شركاء الصفحة الرئيسية",
  "Live Streamers": "منشئو البث",
  "Roster Members": "أعضاء الطاقم",
  "Famous Characters": "الشخصيات المشهورة",
  "Terms of Service": "شروط الخدمة",
  "Support Tickets": "تذاكر الدعم",
  "News Posts": "منشورات الأخبار",
  "Career Positions": "وظائف التقديم",
  "Application Sections": "أقسام التقديم",
  "Application Questions": "أسئلة التقديم",
  "Website Users": "مستخدمو الموقع",
  "Add Staff": "إضافة إداري",
  "Save Staff": "حفظ الإداري",
  "Add Record": "إضافة سجل",
  Save: "حفظ",
  Delete: "حذف",
  Add: "إضافة",
  Search: "بحث",
  "Add Note": "إضافة ملاحظة",
  "Edit News Post": "تعديل الخبر",
  "New News Post": "خبر جديد",
  "Save Post": "حفظ الخبر",
  "No records yet. Add one below.": "لا توجد سجلات بعد. أضف سجلا من الأسفل.",
  "Welcome back": "مرحبا بعودتك",
  "Registered Users": "المستخدمون المسجلون",
  "Total Characters": "إجمالي الشخصيات",
  "Pending Comments": "التعليقات المعلقة",
  "Server Status": "حالة الخادم",
  Offline: "غير متصل",
  "Live now": "مباشر الآن",
  "Check status": "تحقق من الحالة",
  "Latest News": "آخر الأخبار",
  "Edit Homepage": "تعديل الرئيسية",
  "Post News": "نشر خبر",
  Navigate: "التنقل",
  Resources: "الموارد",
  "Stay Updated": "ابق على اطلاع",
  Rules: "القوانين",
  "Get the latest news and event announcements from Gotham City.": "تابع آخر الأخبار وإعلانات الفعاليات من مدينة جوثام.",
  Join: "انضمام",
  "Created with Love by A2 Studio": "صنع بحب بواسطة A2 Studio",
  "View Careers Portal": "عرض بوابة التوظيف",
  "No career positions are posted right now.": "لا توجد وظائف منشورة حاليا.",
  "No news posts are published yet.": "لا توجد أخبار منشورة بعد.",
  "Read more": "اقرأ المزيد",
  "Need Support? Open a Ticket": "تحتاج مساعدة؟ افتح تذكرة",
  "Create Account": "إنشاء حساب",
  "Your Story in Gotham City Starts Tonight": "قصتك في مدينة جوثام تبدأ الليلة",
  "Create your account, link Steam and Discord, and step into the city.": "أنشئ حسابك، اربط Steam وDiscord، وادخل إلى المدينة.",
  "Trusted city allies": "حلفاء المدينة الموثوقون",
  active: "نشط",
  "Community partner": "شريك المجتمع",
  Connecting: "جار الاتصال",
  "Connecting...": "جار الاتصال...",
  Updated: "آخر تحديث",
  live: "مباشر",
  listed: "مدرج",
  "total viewers": "إجمالي المشاهدين",
  viewers: "مشاهد",
  Open: "فتح",
  "Stream offline": "البث غير متصل",
  "The status service could not reach the FiveM endpoints.": "تعذر على خدمة الحالة الوصول إلى روابط FiveM.",
  Select: "اختيار",
  "Hero Section": "قسم الواجهة الرئيسية",
  Stats: "الإحصائيات",
  Header: "العنوان",
  Features: "المميزات",
  Departments: "الأقسام",
  "Journey Header": "عنوان القصة",
  Timeline: "الخط الزمني",
  "Open Positions": "الوظائف المفتوحة",
  Questions: "الأسئلة",
  "Color Theme": "ألوان الموقع",
  "Quick Presets": "إعدادات سريعة",
  Branding: "الهوية",
  "Site Configuration": "إعدادات الموقع",
  "Danger Zone": "منطقة الخطر",
  "Hero Title Line 1": "سطر عنوان الواجهة 1",
  "Hero Title Line 2": "سطر عنوان الواجهة 2",
  "Hero Description": "وصف الواجهة",
  "Server IP": "عنوان الخادم",
  "Discord Link": "رابط ديسكورد",
  "FiveM Connect Link": "رابط اتصال FiveM",
  "Store Link": "رابط المتجر",
  Subtitle: "العنوان الفرعي",
  Title: "العنوان",
  Description: "الوصف",
  "Site Name": "اسم الموقع",
  Tagline: "الشعار النصي",
  "CTA Title": "عنوان الدعوة",
  "CTA Description": "وصف الدعوة",
  "Website Name": "اسم الموقع",
  "Hero Subtitle": "العنوان الفرعي للواجهة",
  "Website Logo URL": "رابط شعار الموقع",
  "Favicon URL": "رابط أيقونة الموقع",
  "Hero Background URL": "رابط خلفية الواجهة",
  "Join Discord Link": "رابط الانضمام لديسكورد",
  "Save Settings": "حفظ الإعدادات",
  "Clear Saved Page Content": "مسح محتوى الصفحات المحفوظ",
  "Clear Saved Content": "مسح المحتوى المحفوظ",
  "partner name": "اسم الشريك",
  "logo url": "رابط الشعار",
  "website url": "رابط الموقع",
  "sort order": "ترتيب العرض",
  "is visible": "ظاهر",
  name: "الاسم",
  "role title": "المسمى",
  category: "الفئة",
  "profile image url": "رابط صورة الحساب",
  "banner url": "رابط الغلاف",
  bio: "النبذة",
  "discord url": "رابط ديسكورد",
  "twitch url": "رابط تويتش",
  "kick url": "رابط كيك",
  "youtube url": "رابط يوتيوب",
  "instagram url": "رابط إنستغرام",
  "x url": "رابط X",
  content: "المحتوى",
  version: "الإصدار",
  "effective date": "تاريخ السريان",
  "is featured": "مميز",
  "is approved": "معتمد",
  "is hidden": "مخفي",
  "An immersive CFW Roleplay community built for deep stories, serious roleplay, and a cinematic city experience.": "مجتمع CFW Roleplay غامر مبني للقصص العميقة، والتمثيل الجاد، وتجربة مدينة سينمائية.",
  "Connect Now": "اتصل الآن",
  "Copied!": "تم النسخ!",
  "Now Live": "متاح الآن",
  "Season 4: Gotham Nights": "الموسم الرابع: ليالي جوثام",
  Players: "اللاعبون",
  "Open Roles": "الوظائف المفتوحة",
  "Staff Members": "أعضاء الطاقم",
  "Built for Serious Roleplayers": "مصمم للاعبي الرول بلاي الجادين",
  "Why Gotham": "لماذا جوثام",
  "Our Roster": "طاقمنا",
  Community: "المجتمع",
  "Meet the people keeping Gotham City running.": "تعرّف على الأشخاص الذين يحافظون على سير مدينة جوثام.",
  "Live Server": "الخادم المباشر",
  "Legends of the City": "أساطير المدينة",
  Bulletin: "النشرة",
  "Join the Team": "انضم إلى الفريق",
  "Frequently Asked Questions": "الأسئلة الشائعة",
  "Need Help": "تحتاج مساعدة",
  "Server Online": "الخادم متصل",
  "Server Offline": "الخادم غير متصل",
  "Server status not configured": "حالة الخادم غير مهيأة",
  "Automatic refresh every 15 seconds": "تحديث تلقائي كل 15 ثانية",
  "Total Stream Viewers": "إجمالي مشاهدي البث",
  Creators: "صناع المحتوى",
  "Community Streamers": "بثوث المجتمع",
  "No streamers added yet": "لم تتم إضافة بثوث بعد",
  "Add Kick or Twitch channels from the admin Streamers page.": "أضف قنوات Kick أو Twitch من صفحة البثوث في الإدارة.",
  Online: "متصل",
  "Max Players": "أقصى عدد لاعبين",
  Queue: "الانتظار",
  Latency: "زمن الاستجابة",
  "Server capacity": "سعة الخادم",
  "No roster members added yet": "لم تتم إضافة أعضاء للطاقم بعد",
  "Add roster profiles from the admin panel.": "أضف ملفات الطاقم من لوحة الإدارة.",
  Discord: "ديسكورد",
  Twitch: "تويتش",
  Kick: "كيك",
  YouTube: "يوتيوب",
  Instagram: "إنستغرام",
  Staff: "الطاقم",
  Owner: "المالك",
  "Master Admin": "المدير الرئيسي",
  Player: "لاعب",
  "Terms page": "صفحة الشروط",
  "No Terms of Service has been published yet. Add one from Admin > Terms.": "لم يتم نشر شروط الخدمة بعد. أضفها من الإدارة > الشروط.",
  "Welcome back, Citizen": "مرحبا بعودتك أيها المواطن",
  "Sign in to access your Gotham City dashboard.": "سجل دخولك للوصول إلى لوحة مدينة جوثام.",
  "Create your account": "أنشئ حسابك",
  "Join Gotham City and step into the city.": "انضم إلى مدينة جوثام وادخل إلى المدينة.",
  "Your story in": "قصتك في",
  "Gotham City awaits.": "مدينة جوثام بانتظارك.",
  "Secure account with linked Discord & Steam": "حساب آمن مرتبط بديسكورد وستيم",
  "Join 15,000+ active roleplay community members": "انضم إلى أكثر من 15,000 عضو نشط في مجتمع الرول بلاي",
  "Access your dashboard, characters & tickets": "ادخل إلى لوحتك وشخصياتك وتذاكرك",
  "Email Address": "البريد الإلكتروني",
  Password: "كلمة المرور",
  "Forgot password?": "نسيت كلمة المرور؟",
  "Signing in...": "جار تسجيل الدخول...",
  "Sign In": "تسجيل الدخول",
  "Or continue with": "أو تابع باستخدام",
  "Don't have an account?": "ليس لديك حساب؟",
  "Create one": "أنشئ حسابا",
  Username: "اسم المستخدم",
  Confirm: "تأكيد",
  "I agree to the Gotham City community rules, terms of service, and privacy policy.": "أوافق على قوانين مجتمع جوثام، وشروط الخدمة، وسياسة الخصوصية.",
  "Creating account...": "جار إنشاء الحساب...",
  "Already have an account?": "لديك حساب بالفعل؟",
  "Sign in": "سجل الدخول",
  Legal: "القانوني",
  Version: "الإصدار",
  Effective: "ساري من",
  "Loading latest terms": "جار تحميل أحدث الشروط",
  "Could not load Terms of Service.": "تعذر تحميل شروط الخدمة.",
  "Premium FiveM Roleplay": "رول بلاي FiveM مميز",
  Enter: "ادخل",
  "A premium dark FiveM roleplay city built for serious stories, creator energy, deep systems, and players who want every scene to matter.": "مدينة FiveM رول بلاي داكنة ومميزة، مبنية للقصص الجادة، وطاقة صناع المحتوى، والأنظمة العميقة، ولكل لاعب يريد أن يكون لكل مشهد قيمة.",
  "Edit these homepage panels from the admin panel to match your server.": "عدّل هذه اللوحات من لوحة الإدارة لتناسب سيرفرك.",
  "Server Identity": "هوية السيرفر",
  "Describe what makes your community different.": "اكتب ما الذي يجعل مجتمعك مختلفا.",
  "Describe your player culture, staff approach, and roleplay standards.": "اكتب ثقافة اللاعبين، أسلوب الإدارة، ومعايير الرول بلاي.",
  "Custom Systems": "أنظمة مخصصة",
  "Describe your scripts, jobs, vehicles, interiors, or city features.": "اكتب السكربتات، الوظائف، المركبات، الأماكن الداخلية، أو مميزات المدينة.",
  "Check the current FiveM server status, capacity, queue, and latest update time.": "تابع حالة سيرفر FiveM الحالية، السعة، قائمة الانتظار، وآخر تحديث.",
  "Open positions posted by staff appear here.": "الوظائف التي تنشرها الإدارة تظهر هنا.",
  "No story milestones are published yet.": "لم يتم نشر محطات القصة بعد.",
  "Scroll roadmap": "حرّك الخريطة",
  "New Milestone": "محطة جديدة",
  test: "اختبار",
  "test Description": "وصف اختباري",
  Featured: "مميز",
  Character: "شخصية",
  Announcement: "إعلان",
  Update: "تحديث",
  Event: "فعالية",
  "Login to vote": "سجل الدخول للتصويت",
  "Login to comment": "سجل الدخول للتعليق",
  "Comment submitted for approval": "تم إرسال التعليق للمراجعة",
  "Comment posted": "تم نشر التعليق",
  Failed: "فشل",
  comments: "تعليقات",
  "Write a comment...": "اكتب تعليقا...",
  "Post Comment": "نشر التعليق",
  "No comments yet. Be the first to reply.": "لا توجد تعليقات بعد. كن أول من يرد.",
  "Loading open positions...": "جار تحميل الوظائف المفتوحة...",
  "No open positions are posted right now.": "لا توجد وظائف مفتوحة حاليا.",
  "Open Position": "وظيفة مفتوحة",
  Department: "القسم",
  Apply: "تقديم",
  Closed: "مغلق",
  "No news posts yet. Check back soon.": "لا توجد أخبار حاليا. عد لاحقا.",
  Pinned: "مثبت",
  "Back to careers": "العودة إلى التوظيف",
  "Loading application...": "جار تحميل نموذج التقديم...",
  "This position could not be found.": "تعذر العثور على هذه الوظيفة.",
  Requirements: "المتطلبات",
  "You need to log in before submitting. You can still read the questions here.": "يجب تسجيل الدخول قبل الإرسال. يمكنك قراءة الأسئلة هنا.",
  "Required questions are marked with an asterisk.": "الأسئلة المطلوبة مميزة بعلامة نجمة.",
  "Submit Application": "إرسال الطلب",
  "Log in to Submit": "سجل الدخول للإرسال",
  "Submitting...": "جار الإرسال...",
  "Please answer all required questions.": "يرجى الإجابة عن كل الأسئلة المطلوبة.",
  "Application submitted. You can track it from your dashboard.": "تم إرسال الطلب. يمكنك متابعته من لوحة اللاعب.",
  "Could not submit application.": "تعذر إرسال الطلب.",
  Name: "الاسم",
  Age: "العمر",
  "Discord ID": "معرف ديسكورد",
  "Why should we pick you?": "لماذا يجب أن نختارك؟",
  "Why do you want this role?": "لماذا تريد هذا الدور؟",
  "Do you have previous FiveM or roleplay experience?": "هل لديك خبرة سابقة في FiveM أو الرول بلاي؟",
  "How active can you be weekly?": "كم يمكنك أن تكون نشطا أسبوعيا؟",
  "How do you handle conflict with other players?": "كيف تتعامل مع الخلاف مع اللاعبين الآخرين؟",
  "Do you agree to follow server rules and staff instructions?": "هل توافق على اتباع قوانين السيرفر وتعليمات الإدارة؟",
  "Optional extra notes": "ملاحظات إضافية اختيارية",
  Restricted: "مقيد",
  "Login Required": "تسجيل الدخول مطلوب",
  "Please log in to view your FiveM characters.": "يرجى تسجيل الدخول لعرض شخصيات FiveM الخاصة بك.",
  "Link Steam": "ربط Steam",
  "Connect Your Steam Account": "اربط حساب Steam",
  "We match your Steam identity to your FiveM characters. Link Steam to see your characters, inventory, vehicles, and more.": "نربط هوية Steam الخاصة بك بشخصيات FiveM لعرض الشخصيات والمخزون والمركبات والمزيد.",
  "Go to Dashboard": "الذهاب إلى لوحة اللاعب",
  "My Server Data": "بياناتي في السيرفر",
  "My Characters": "شخصياتي",
  "No Characters Found": "لم يتم العثور على شخصيات",
  "Your Steam account doesn't appear to own any characters on this server yet. Join the server and create one!": "يبدو أن حساب Steam الخاص بك لا يملك أي شخصيات في هذا السيرفر حتى الآن. ادخل السيرفر وأنشئ شخصية.",
  Grade: "الرتبة",
  "Character details": "تفاصيل الشخصية",
  "Citizen ID": "رقم المواطن",
  Health: "الصحة",
  Armor: "الدرع",
  Vehicles: "المركبات",
  Plate: "اللوحة",
  Unknown: "غير معروف",
  Inventory: "المخزون",
  Cash: "الكاش",
  Bank: "البنك",
  Playtime: "وقت اللعب",
  "Could not start Discord link. Please try again.": "تعذر بدء ربط ديسكورد. حاول مرة أخرى.",
  "Could not start Steam link. Please try again.": "تعذر بدء ربط Steam. حاول مرة أخرى.",
  "Log out": "تسجيل الخروج",
  "Ticket created": "تم إنشاء التذكرة",
  "Could not create ticket": "تعذر إنشاء التذكرة",
  "Here's a snapshot of your Gotham City account. Keep your identifiers linked to unlock in-game character syncing and faster support.": "هذه لمحة عن حسابك في Gotham City. حافظ على ربط معرفاتك لتفعيل مزامنة الشخصيات ودعم أسرع.",
  "Account Status": "حالة الحساب",
  Banned: "محظور",
  "Good Standing": "حالة جيدة",
  "Linked Providers": "الحسابات المرتبطة",
  "Open Tickets": "التذاكر المفتوحة",
  "Account Timeline": "سجل الحساب",
  "Account created": "تم إنشاء الحساب",
  "Discord linked": "ديسكورد مرتبط",
  "Steam linked": "Steam مرتبط",
  Connected: "مرتبط",
  "Not connected": "غير مرتبط",
  "My Applications": "طلباتي",
  "Apply for a Role": "تقديم على دور",
  "Loading applications...": "جار تحميل الطلبات...",
  "No applications submitted yet. Open the careers portal to apply for a position.": "لم ترسل أي طلبات بعد. افتح بوابة التوظيف للتقديم على وظيفة.",
  "Career Application": "طلب توظيف",
  Position: "الوظيفة",
  Submitted: "تم الإرسال",
  recently: "حديثا",
  "Staff Reply": "رد الإدارة",
  "Under review": "قيد المراجعة",
  Approved: "مقبول",
  Denied: "مرفوض",
  Pending: "قيد الانتظار",
  "Link Steam to view characters": "اربط Steam لعرض الشخصيات",
  "Connect your Steam account to sync your in-game CFW characters, job, and balances directly to your dashboard.": "اربط حساب Steam لمزامنة شخصيات CFW والوظيفة والأرصدة مباشرة إلى لوحة اللاعب.",
  "Connect Steam": "ربط Steam",
  "View full health, armor & inventory details": "عرض تفاصيل الصحة والدرع والمخزون كاملة",
  "Finishing login": "جار إنهاء تسجيل الدخول",
  "Connecting your account to Gotham City.": "جار ربط حسابك مع Gotham City.",
  "Login session expired or was opened from an old link. Please start Discord login again.": "انتهت جلسة الدخول أو تم فتحها من رابط قديم. ابدأ تسجيل دخول ديسكورد مرة أخرى.",
  "Steam login session expired or was opened from an old link. Please start Steam login again.": "انتهت جلسة Steam أو تم فتحها من رابط قديم. ابدأ تسجيل دخول Steam مرة أخرى.",
  "Steam could not verify the login response. Please try again from the website.": "تعذر على Steam تأكيد تسجيل الدخول. حاول مرة أخرى من الموقع.",
  "Could not finish login. Please try again.": "تعذر إكمال تسجيل الدخول. حاول مرة أخرى.",
  "Missing login token from the backend.": "رمز تسجيل الدخول مفقود من الباكند.",
  "Back to login": "العودة لتسجيل الدخول",
  "Back to dashboard": "العودة إلى لوحة اللاعب",
  "Please wait while we verify your login.": "يرجى الانتظار بينما نتحقق من تسجيل الدخول.",
};

type LanguageContextValue = {
  language: Language;
  isArabic: boolean;
  dir: "ltr" | "rtl";
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (value?: string | number | null) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    return window.localStorage.getItem("gotham_language") === "ar" ? "ar" : "en";
  });

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    if (typeof window !== "undefined") window.localStorage.setItem("gotham_language", next);
  };

  useEffect(() => {
    document.documentElement.lang = language === "ar" ? "ar" : "en";
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    isArabic: language === "ar",
    dir: language === "ar" ? "rtl" : "ltr",
    setLanguage,
    toggleLanguage: () => setLanguage(language === "ar" ? "en" : "ar"),
    t: (input) => {
      const text = String(input ?? "");
      if (language !== "ar") return text;
      return AR[text] || text;
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
