INSERT IGNORE INTO web_roles (id, name, description, is_system, sort_order) VALUES
('role-player', 'Player', 'Default player account.', 1, 100),
('role-support', 'Support', 'Ticket and application support.', 1, 50),
('role-admin', 'Admin', 'Website administrator.', 1, 10),
('role-super-admin', 'Super Admin', 'All non-master admin permissions.', 1, 5),
('role-master-admin', 'Master Admin', 'Full master access.', 1, 1);

INSERT IGNORE INTO web_permissions (id, name, category) VALUES
('perm-view-player-portal', 'view_player_portal', 'player'),
('perm-manage-home', 'manage_home', 'cms'),
('perm-manage-partners', 'manage_partners', 'cms'),
('perm-manage-journey', 'manage_journey', 'cms'),
('perm-manage-famous', 'manage_famous', 'cms'),
('perm-manage-roster', 'manage_roster', 'creators'),
('perm-manage-live', 'manage_live', 'creators'),
('perm-manage-team', 'manage_team', 'cms'),
('perm-manage-careers', 'manage_careers', 'careers'),
('perm-review-career-applications', 'review_career_applications', 'careers'),
('perm-manage-tickets', 'manage_tickets', 'support'),
('perm-close-tickets', 'close_tickets', 'support'),
('perm-manage-news', 'manage_news', 'cms'),
('perm-manage-map', 'manage_map', 'cms'),
('perm-manage-faq', 'manage_faq', 'cms'),
('perm-manage-terms', 'manage_terms', 'legal'),
('perm-manage-events', 'manage_events', 'cms'),
('perm-manage-users', 'manage_users', 'security'),
('perm-manage-admins', 'manage_admins', 'security'),
('perm-manage-permissions', 'manage_permissions', 'security'),
('perm-manage-theme', 'manage_theme', 'cms'),
('perm-manage-webhooks', 'manage_webhooks', 'integrations'),
('perm-view-audit-logs', 'view_audit_logs', 'security'),
('perm-master-access', 'master_access', 'security');
